CC?="cc"
all: aufg1 aufg2 aufg3 aufg4 aufg5 aufg6 aufg7 aufg8_1 aufg8_2
.PHONY: all

%: %.c
	$(CC) -o $@ $^

.PHONY: clean
clean:
	rm -f aufg1 aufg2 aufg3 aufg4 aufg5 aufg6 aufg7 aufg8_1 aufg8_2
	rm -f *~
