all: ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8

aufg1: ex1

aufg2: ex2

aufg3: ex3

aufg4: ex4

aufg5: ex5

aufg6: ex6

aufg7: ex7

aufg8: ex8

ex1:
	gcc -o ex1 aufg1.c

ex2:
	gcc -o ex2 aufg2.c

ex3:
	gcc -o ex3 aufg3.c

ex4:
	gcc -o ex4 aufg4.c

ex5:
	gcc -o ex5 aufg5.c

ex6:
	gcc -o ex6 aufg6.c

ex7:
	gcc -o ex7 aufg7.c

ex8:
	gcc -o ex81 aufg8_1.c
	gcc -o ex82 aufg8_2.c

clean:
	rm -f ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex81 ex82 *~
